### ISSUE TITLE
Enabling multiple interrupt causes multiple triggering even when only one should be triggered

### ISSUE THREAD

**Issue by souellet-ms** [I-SYST/EHAL#19]
Using EHAL for Nordic nRF52.

When enabling multiple interrupt using IOPinEnableInterrupt with different Interrupt number, if we trigger an interrupt by applying the desired transition on a specific pin, the GPIOTE_IRQHandler called all assigned callback for all PIN, instead of only the triggered pin. The IRQHandler should not check for either EVENTS_IN or EVENTS_PORT is valid but the condition should be separated, in order to detect specific pin interrupt (EVENTS_IN) and sense detect (EVENTS_PORT) separately since a EVENTS_IN interrupt will always trigger EVENTS_PORT.

**Comment by hnhoan** [comment]
ac98fdde0ee951cf57528c7b4768d1a3ff9646e4
