### ISSUE TITLE
nRF 51 library 'SVCALL' syntax error

### ISSUE THREAD

**Issue by peti634** [I-SYST/EHAL#31]
Hi,

I have tried to compile the IOsonata_nRF51 library, but I received this error:

`../../../../../../../external/nRF5_SDK_12/components/softdevice/s130/headers/ble_gap.h:1452:1: note: in expansion of macro 'SVCALL'
 SVCALL(SD_BLE_GAP_LESC_DHKEY_REPLY, uint32_t, sd_ble_gap_lesc_dhkey_reply(uint16_t conn_handle, ble_gap_lesc_dhkey_t const *p_dhkey));
 ^
../../../../../../../external/nRF5_SDK_12/components/softdevice/s130/headers/nrf_svc.h:69:6: error: impossible constraint in 'asm'`

ARM-GCC: 10.2.1 20201103
OS: Windows 7
SDK: nRF5_SDK_12.3.0_d7731ad

Do you have any idea?
Thank you!

**Comment by hnhoan** [comment]
Open the file nrf_svc.h in the softdevice headers of the SDK, change the line 55
from 
#define GCC_CAST_CPP (uint8_t)
to
#define GCC_CAST_CPP (uint16_t)

**Comment by peti634** [comment]
Cool, it is work!
Thank you!

**Comment by peti634** [comment]
I have built a "blinky" project, but it doesnt work.

	IOPinConfig(0, 11, 0, IOPINDIR_OUTPUT,0, 0);
	IOPinSet(0, 11);

	while (true)
	{
	}
	
I have built same project in uVision:
```
  nrf_gpio_cfg_output(11);
  nrf_gpio_pin_write(11, 1);
  while (true)
  {
  }
```
    
But it is work.

**Comment by hnhoan** [comment]
Do you see it flashing with this ? 
```
	while (1)
	{
		IOPinSet(0, 11);
		msDelay(250);
		IOPinClear(0, 11);
		msDelay(250);
	}

```

**Comment by peti634** [comment]
No.
It looks like that processor not starting, because the PIN is floating, I cant measure GND or VCC on this pin.

**Comment by hnhoan** [comment]
Are you running from within Eclipse ? If not compile the Release build instead.  Debug build enabled the semihosting which requires you to run with the debugger which mean you need to run it with Eclipse debug configuration.  The Release build is configured for free running.

**Comment by peti634** [comment]
No, I not running in Ecliplse, only use the J-link and J-flash.
Which NRF SDK do you recommend?

**Comment by hnhoan** [comment]
As I said, you need to compile the Release build for that to use outside of Eclipse. 
SDK12  is the last available for nRF51 series.  nRF51 is at end of life.

**Comment by peti634** [comment]
The problem is same.

I use the nRF5_SDK_12.3.0_d7731ad
Change the GCC_CAST_CPP in nrf_svc.h

But I have more problem:
"error: 'min' was not declared in this scope" in src/imu/imu_invn_icm20948.cpp:332 and src/sensors/agm_invn_icm20948.cpp:435
Fix: `#define min(a,b) (((a)<(b))?(a):(b))`

"`sorry, unimplemented: non-trivial designated initializers not supported`" in
ARM/Nordic/src/blueio_blesrvc.cpp: 86, 139, 193, 257
ARM/Nordic/src/uart_bleintrf.cpp: 90, 165
Fix:
From:
```
const BleSrvcCfg_t s_BlueIOIoSrvcCfg = {
	.SecType = BLESRVC_SECTYPE_NONE,		// Secure or Open service/char
	.UuidBase = BLUEIO_UUID_BASE,			// Base UUID
	.UuidSvc = BLUEIO_UUID_IO_SERVICE,			// Service UUID
	....
```
To:
```
const BleSrvcCfg_t s_BlueIOIoSrvcCfg = {
	.SecType = BLESRVC_SECTYPE_NONE,		// Secure or Open service/char
	.UuidBase = BLUEIO_UUID_BASE,			// Base UUID
	.NbUuidBase = 16,
	.UuidSvc = BLUEIO_UUID_IO_SERVICE,			// Service UUID
```
	

Is it correct?
Thank you!

**Comment by hnhoan** [comment]
> "error: 'min' was not declared in this scope" in src/imu/imu_invn_icm20948.cpp:332 and src/sensors/agm_invn_icm20948.cpp:435

Not sure why you get this error.  the min/max are define in istddef.h of IOsonata/include. I did not get that error when I compiled.

the s_BlueIOIoSrvcCfg should be
```
const BleSrvcCfg_t s_BlueIOIoSrvcCfg = {
	.SecType = BLESRVC_SECTYPE_NONE,		// Secure or Open service/char
	.UuidBase = {BLUEIO_UUID_BASE,},			// Base UUID
	.NbUuidBase = 1,
	.UuidSvc = BLUEIO_UUID_IO_SERVICE,			// Service UUID

```

**Comment by peti634** [comment]
Thank you, it works!
After I have do it, and I have build Release.
